accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("delete/", views.delete, name="delete"),
    path("update/", views.update, name="update"),
    path("password/", views.change_password, name="change_password"),
]

articles/urls.py
from django.urls import path
from . import views

app_name = "articles"
urlpatterns = [
    path("", views.articles, name="articles"),
    path("create/", views.create, name="create"),
    path("<int:pk>/", views.article_detail, name="article_detail"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/comments/", views.comment_create, name="comment_create"),
    path(
        "<int:pk>/comments/<int:comment_pk>/delete/",
        views.comment_delete,
        name="comment_delete",
    ),
    path("<int:pk>/like/", views.like, name="like"),
    path("index/", views.index, name="index"),
    #
    path("data-throw/", views.data_throw, name="throw"),
    path("data-catch/", views.data_catch, name="catch"),
]

djangoex/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

from articles import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("index/", views.index, name="index"),
    path("articles/", include("articles.urls")),
    path("users/", include("users.urls")),
    path("accounts/", include("accounts.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path("", views.users, name="users"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("<int:user_id>/follow/", views.follow, name="follow"),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <title>MY DJANGO</title>

    {% block head %}{% endblock head %}
</head>
<body>

    <div class="navbar">

        {% if request.user.is_authenticated %}
            <h3>Hello, {{ request.user.username }}</h3>
            <form action="{% url 'accounts:logout' %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="로그아웃"></input>
            </form>
            
            <a href="{% url "accounts:update" %}">회원정보수정</a>

            <form action="{% url "accounts:delete" %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="회원탈퇴"></input>
            </form>
        {% else %}
            <a href="{% url 'accounts:login' %}">로그인</a>
            <a href="{% url "accounts:signup" %}">회원가입</a>
        {% endif %}

    </div>

    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
        
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <h1>INDEX PAGE</h1>

  <img src="{% static "articles/teddy-bear.png" %}">
  
  <ul>
    <li><a href="{% url 'articles:articles' %}">글목록</a></li>
    <li><a href="{% url 'articles:throw' %}">Throw</a></li>
    <li><a href="{% url 'users:users' %}">Users</a></li>
  </ul>

{% endblock content %}