articles/urls.py
from django.urls import path
from . import views

app_name = "articles"
urlpatterns = [
    path("", views.articles, name="articles"),
    path("create/", views.create, name="create"),
    path("<int:pk>/", views.article_detail, name="article_detail"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/comments/", views.comment_create, name="comment_create"),
    path(
        "<int:pk>/comments/<int:comment_pk>/delete/",
        views.comment_delete,
        name="comment_delete",
    ),
    path("<int:pk>/like/", views.like, name="like"),
    path("index/", views.index, name="index"),
    #
    path("data-throw/", views.data_throw, name="throw"),
    path("data-catch/", views.data_catch, name="catch"),
]

djangoex/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

from articles import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("index/", views.index, name="index"),
    path("articles/", include("articles.urls")),
    path("users/", include("users.urls")),
    path("accounts/", include("accounts.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path("", views.users, name="users"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("<int:user_id>/follow/", views.follow, name="follow"),
]

articles/models.py
from django.db import models
from django.conf import settings


class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to="images/", blank=True)

    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="articles"
    )

    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_articles"
    )

    def __str__(self):
        return self.title


class Comment(models.Model):
    article = models.ForeignKey(
        Article, on_delete=models.CASCADE, related_name="comments"
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="comments"
    )
    content = models.CharField(max_length=120)
    created_at = models.DateTimeField(auto_now_add=True)
    updaetd_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

articles/forms.py
from django import forms
from .models import Article, Comment


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = "__all__"
        exclude = ("author",)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = "__all__"
        exclude = ("article", "user")

articles/views.py
from django.shortcuts import redirect, render, get_object_or_404
from .models import Article, Comment
from .forms import ArticleForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_POST


def index(request):
    return render(request, "articles/index.html")


def articles(request):
    articles = Article.objects.all().order_by("-pk")
    context = {
        "articles": articles,
    }
    return render(request, "articles/articles.html", context)


def article_detail(request, pk):
    article = get_object_or_404(Article, pk=pk)
    comment_form = CommentForm()
    comments = article.comments.all().order_by("-pk")
    context = {
        "article": article,
        "comment_form": comment_form,
        "comments": comments,
    }
    return render(request, "articles/article_detail.html", context)


@login_required
def create(request):
    if request.method == "POST":
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.author = request.user
            article.save()
            return redirect("articles:article_detail", article.pk)
    else:
        form = ArticleForm()

    context = {"form": form}
    return render(request, "articles/create.html", context)


@login_required
@require_http_methods(["GET", "POST"])
def update(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if article.author != request.user:
        if request.method == "POST":
            form = ArticleForm(request.POST, instance=article)
            if form.is_valid():
                article = form.save()
                return redirect("articles:article_detail", article.pk)
        else:
            form = ArticleForm(instance=article)
    else:
        return redirect("articles:articles")

    context = {
        "form": form,
        "article": article,
    }
    return render(request, "articles/update.html", context)


@require_POST
def delete(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.user.is_authenticated:
        if article.author == request.user:
            article = get_object_or_404(Article, pk=pk)
            article.delete()
    return redirect("articles:articles")


@require_POST
def comment_create(request, pk):
    article = get_object_or_404(Article, pk=pk)
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.article = article
        comment.user = request.user
        comment.save()
        return redirect("articles:article_detail", article.pk)


@require_POST
def comment_delete(request, pk, comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_pk)
        if comment.user == request.user:
            comment.delete()
    return redirect("articles:article_detail", pk)


@require_POST
def like(request, pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=pk)
        if article.like_users.filter(pk=request.user.pk).exists():
            article.like_users.remove(request.user)  # 좋아요 취소
        else:
            article.like_users.add(request.user)  # 좋아요
        return redirect("articles:articles")
    return redirect("accounts:login")


def data_throw(request):
    return render(request, "articles/data_throw.html")


def data_catch(request):
    data = request.GET.get("message")
    context = {
        "data": data,
    }
    return render(request, "articles/data_catch.html", context)

articles/templates/article_detail.html
{% extends "base.html" %}

{% block content %}

    <h2>글 상세 페이지</h2>
    <p>제목: {{ article.title }}</p>
    <p>내용: {{ article.content }}</p>
    <p>작성일시: {{ article.create_at }}</p>
    <p>수정일시: {{ article.update_at }}</p>
    {% if article.image %}
        <img src="{{ article.image.url }}">
    {% endif %}
    <a href="{% url 'articles:articles' %}">
        <button>목록 1보기</button>
    </a>

    <a href="{% url 'articles:update' article.pk %}">
        <button>글수정</button>
    </a>
    <hr>
    <form action="{% url 'articles:delete' article.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="글삭제">
    </form>

    -----
    <hr>
<hr>
<h3>댓글</h3>
<form action="{% url "articles:comment_create" article.pk %}" method="POST">
    {% csrf_token %}
    {{ comment_form.as_p }}
    <input type="submit" value="댓글작성">
</form>
<ul>
    {% for comment in comments %}
        <li>
            <p>{{ comment.content }}</p>
        </li>
    {% endfor %}
</ul>
{% endblock content %}

articles/templates/articles.html
{% extends 'base.html' %}
{% block content %}
    <h1>Articles</h1>
    <a href="{% url 'articles:create' %}">새 글 작성</a>

    <ul>
        {% for article in articles %}


            <form actions="{% url "article:like" article.pk %}" method="POST">
                {% csrf_token %}
                {% if user in article.like_users.all %}
                    <input type="sumit" value="좋아요 취소">
                {% else %}
                    <input type="sumit" value="좋아요">
                {% endif %}
            </form>

        {% endfor %}
    </ul>

{% endblock content %}

articles/templates/create.html
{% extends "base.html" %}

{% block content %}
	<h1>'{{article.title}}' 작성 완료</h1>
	<a href="{% url 'articles' %}">목록으로</a>
{% endblock content %}

articles/templates/data_catch.html
{% extends 'base.html' %}

{% block content %}
    <h1>Data Catch</h1>

    <div>
        <h2>Current Data</h2>
        <p>Current data is: {{ data }}</p>
    </div>
    <a href="/articles/data-throw/">다시 데이터 보내러가기</a>

{% endblock content %}

articles/templates/data_throw.html
{% extends "base.html" %}
{% block content %}
    <form action="{% url "catch" %}" method="GET">
        <label for="message">메세지 입력</label>
        <input type="text" id="message" name="message">
        <button type="submit">전송</button>
    </form>
{% endblock content %}

articles/templates/detail.html
{% extends "base.html" %}

{% block content %}

    <h2>글 상세 페이지</h2>
    <p>제목: {{ article.title }}</p>
    <p>내용: {{ article.content }}</p>
    <p>작성일시: {{ article.created_at }}</p>
    <p>수정일시: {{ article.updated_at }}</p>

    <a href="{% url 'articles:articles' %}">
        <button>목록 1보기</button>
    </a>

    <a href="{% url 'articles:edit' article.pk %}">
        <button>글수정</button>
    </a>
    <hr>
    <form action="{% url 'articles:delete' article.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="글삭제">
    </form>

{% endblock content %}

articles/templates/edit.html
{% extends "base.html" %}


{% block content %}
<h1>Update Article</h1>

<form action="{% url 'update' article.pk %}" method="POST">
	  {% csrf_token %}
    <label for="title">제목</label>
    <input type="text" name="title" id="title" value={{ article.title }}><br><br>

    <label for="content">내용</label>
    <textarea name="content" id="content" cols="30" rows="10">{{ article.content }}</textarea><br><br>

    <button type="submit">저장</button>
</form>


{% endblock content %}

articles/templates/hello.html
{% extends "base.html" %}
{% block content %}
    <h1>Hello, {{ name }}</h1>
    <p>태그 {{ tags }}</p>
    <ul>
        {% for book in books %}
            <li>{{ book }}</li>
        {% endfor %}
    </ul>
{% endblock content %}

articles/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <img src="">
    <img src="{% static "123.jpg" %}" alt="teby">
    <ul>
{#        <li><a href="{% url 'hello' %}">Hello</a></li>#}
        <li><a href="{% url 'articles:throw' %}">Throw</a></li>
        <li><a href="{% url 'articles:articles' %}">목록 보기</a></li>

    </ul>
{% endblock content %}

articles/templates/new.html
{% extends "base.html" %}


{% block content %}
    <h1>New Article</h1>

    <form action="{% url 'articles:create' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">저장</button>
    </form>

    <a href="{% url 'articles:articles' %}">목록으로</a>
{% endblock content %}

articles/templates/update.html
{% extends "base.html" %}

{% block content %}
<h1>Update Article</h1>

<form action="{% url 'articles:update' article.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">수정</button>
</form>

<a href="{% url 'articles:article_detail' article.pk %}">이전으로</a>
{% endblock content %}